asset/urls.py
from django.conf.urls import include, url
from asset import views

urlpatterns = [
    url(r'report/$', views.asset_report, name='asset_report'),
    # url(r'report/bulk_create/$',views.bulk_create_assets,name='bulk_create_assets' ),
    url(r'report/asset_with_no_asset_id/$', views.asset_with_no_asset_id, name='acquire_asset_id'),
    url(r'^report_test/$', views.asset_report_test),
    url(r'^acquire_asset_id_test/$', views.acquire_asset_id_test),
    url(r'^new_assets/approval/$', views.new_assets_approval, name="new_assets_approval"),
    url(r'^asset_list/$', views.asset_list, name="asset_list"),
    url(r'^asset_list/(\d+)/$', views.asset_detail, name="asset_detail"),
    url(r'^asset_list/list/$', views.get_asset_list, name="get_asset_list"),
    url(r'^asset_list/category/$', views.asset_category, name="asset_category"),
    url(r'^asset_event_logs/(\d+)/$', views.asset_event_logs, name="asset_event_logs"),

]

assets/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
#  Author: Jason Wang
from django.conf.urls import url
from assets import views
urlpatterns = [
    #列表展示
    url(r'^assetslist/', views.assetslist,name='assetslist',),
    url(r'^assetsarea', views.assetsarea,name='assetsarea',),
    url(r'^netlist', views.netlist,name='netlist',),
    url(r'^iplist', views.iplist,name='iplist',),
    url(r'^modellist/(\d+)', views.modellist,name='modellist',),
    url(r'^cabinet/(\d+)', views.cabinet,name='cabinet',),
    url(r'^idcasset/(\d+)', views.idcasset,name='idcasset',),
    #添加
    url(r'^addarea', views.addarea,name='addarea',),
    #详细信息
    url(r'^hostdetail/(\d+)', views.hostdetail,name='hostdetail',),
    #服务器更新
    url(r'^hostupdate', views.hostupdate,name='hostupdate',),
    url(r'^roomdetail/(\d+)', views.roomdetail,name='roomdetail',),
    #编辑
    url(r'^compilesarea/(\d+)', views.compiles_area,name='compilesarea',),
]

cmdb/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
#  Author: Jason Wang

"""cmdb URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url,include
from django.contrib import admin
from cmdb import view
from api import rest_urls
urlpatterns = [
    url(r'^admin/', admin.site.urls,name='admin'),
    # url(r'^$',view.index,name='index'),
    url(r'^$',view.index,name="dashboard"),
    url(r'^login/$', view.acc_login,name='login',),
    url(r'^logout/$', view.acc_logout,name='logout',),
    url(r'^assets/', include('assets.urls')),
    url(r'^asset/',include('asset.urls')),
    url(r'^install/', include('install.urls')),
    url(r'^userinfo/', include('userinfo.urls')),
    url(r'^log/', include('log.urls')),
    url(r'^api/', include(rest_urls)),
    url(r'^rest_api/', include( 'snippets.urls')),
]

log/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
#  Author: Jason Wang


from django.conf.urls import url
from log import views
urlpatterns = [
    url(r'^assetslogs', views.assetslogs,name='assetslogs',),
    url(r'^executelogs', views.executelogs,name='executelogs',),
    url(r'^loginlogs', views.loginlogs,name='loginlogs',),
]

asset/models.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
#  Author: Jason Wang

# Create your models here.
from django.db import models
from django.contrib.auth.models import User


class UserProfiles(User):
    ''''''
    name = models.CharField("姓名",max_length=32)
    #头像
    head_img = models.ImageField(blank=True,null=True,upload_to="uploads/portrait",verbose_name='头像')
    #邮箱
    # email = models.EmailField(max_length=64,blank=True,null=True,verbose_name='邮箱')
    #手机号
    mobile = models.CharField(verbose_name='手机号',max_length=128,null=True)
    tel =  models.CharField(verbose_name='电话',max_length=128,null=True)
    #部门
    department = models.ForeignKey('Group',verbose_name='部门',null=True,blank=True)
    #秘钥
    secret_key = models.TextField(verbose_name='密钥')
    #备注
    memo = models.TextField(verbose_name='备注', null=True, blank=True)
    #创建时间
    create_date  = models.DateField(verbose_name='注册时间',auto_now=True)
    #是否为激活用户
    # is_active = models.BooleanField(verbose_name='是否激活',default=False)
    valid_begin_time = models.DateField(verbose_name='账户生效日期',blank=True,null=True)
    valid_end_time = models.DateField(verbose_name='账户失效日期',blank=True)
    is_admin = models.BooleanField(verbose_name='是否为管理员',default=False)
    token = models.CharField(verbose_name='秘钥',max_length=32)
    def __str__(self):
        return self.name
    class Meta:
        verbose_name = '成员'
        verbose_name_plural = '成员'
class Group(models.Model):
    #群组名称
    name = models.CharField(max_length=64,verbose_name='部门')
    #负责人
    owner = models.ForeignKey(UserProfiles,verbose_name='负责人')
    #备注
    memo = models.TextField(u'备注', null=True, blank=True)
    def __str__(self):
        return  self.name
    class Meta:
        verbose_name='部门'
        verbose_name_plural = '部门'
    def __str__(self):
        return self.name
    class Meta:
        super(User.Meta)
        verbose_name = '用户'
        verbose_name_plural = "用户"

class Asset(models.Model):
    '''资产信息表'''
    name = models.CharField(max_length=64,unique=True)
    asset_type_choices = (
        ('server', u'服务器'),
        ('networkdevice', u'网络设备'),
        ('storagedevice', u'存储设备'),
        ('securitydevice', u'安全设备'),
        ('securitydevice', u'机房设备'),
        # ('switch', u'交换机'),
        # ('router', u'路由器'),
        # ('firewall', u'防火墙'),
        # ('storage', u'存储设备'),
        # ('NLB', u'NetScaler'),
        # ('wireless', u'无线AP'),
        ('software', u'软件资产'),
        #('others', u'其它类'),
    )
    asset_type = models.CharField(choices=asset_type_choices,max_length=64, default='server')
    business_unit = models.ForeignKey("BusinessUnit",blank=True,null=True)
    sn = models.CharField(u'资产SN号', max_length=128, unique=True)
    manufactory = models.ForeignKey('Manufactory', verbose_name=u'制造商', null=True, blank=True)
    management_ip = models.GenericIPAddressField(u'管理IP',blank=True,null=True)
    contract = models.ForeignKey('Contract', verbose_name=u'合同', null=True, blank=True)
    trade_date = models.DateField(u'购买时间', null=True, blank=True)
    expire_date = models.DateField(u'过保修期', null=True, blank=True)
    price = models.FloatField(u'价格', null=True, blank=True)
    idc = models.ForeignKey('IDC', verbose_name=u'IDC机房',null=True, blank=True)

    admin = models.ForeignKey('UserProfiles', verbose_name='资产管理员', null=True, blank=True)
    memo = models.TextField(u'备注', null=True, blank=True)
    create_date = models.DateTimeField(blank=True, auto_now_add=True)
    update_date = models.DateTimeField(blank=True, auto_now=True)
    class Meta:
        verbose_name = '资产总表'
        verbose_name_plural = "资产总表"


    def __str__(self):
        return '<id:%s name:%s>' % (self.id, self.name)

class Server(models.Model):
    '''服务器信息'''
    asset = models.OneToOneField(Asset)
    sub_assset_type_choices = (
        (0, 'PC服务器'),
        (1, '刀片机'),
        (2, '小型机'),
    )
    sub_asset_type = models.SmallIntegerField(choices=sub_assset_type_choices, verbose_name="服务器类型", default=0)
    created_by_choices = (
        ('auto', 'Auto'),
        ('manual', 'Manual'),
    )
    created_by = models.CharField(choices=created_by_choices,max_length=32,default='auto') #auto: auto created,   manual:created manually
    hosted_on = models.ForeignKey('self', related_name='hosted_on_server', blank=True, null=True)  # for vitural server
    model = models.CharField(verbose_name=u'型号',max_length=128,null=True, blank=True )
    raid_type = models.CharField(u'raid类型',max_length=512, blank=True,null=True)
    os_type = models.CharField(u'操作系统类型', max_length=64, blank=True, null=True)
    os_distribution = models.CharField(u'发型版本', max_length=64, blank=True, null=True)
    os_release = models.CharField(u'操作系统版本', max_length=64, blank=True, null=True)

    class Meta:
        verbose_name = '服务器'
        verbose_name_plural = "服务器"
        # together = ["sn", "asset"]


    def __str__(self):
        return '%s sn:%s' % (self.asset.name, self.asset.sn)

class BusinessUnit(models.Model):
    '''业务线'''
    parent_unit = models.ForeignKey('self',null=True,blank=True)
    name = models.CharField(max_length=64,unique=True)

    def __str__(self):
        return self.name

class SecurityDevice(models.Model):
    asset = models.OneToOneField('Asset')
    sub_assset_type_choices = (
        (0,'防火墙'),
        (1,'入侵检测设备'),
        (2,'互联网网关'),
        (4,'运维审计系统'),
    )
    sub_asset_type = models.SmallIntegerField(choices=sub_assset_type_choices,verbose_name="服务器类型",default=0)

    def __str__(self):
        return self.asset.id

class NetworkDevice(models.Model):
    asset = models.OneToOneField('Asset')
    sub_assset_type_choices = (
        (0,'路由器'),
        (1,'交换机'),
        (2,'负载均衡'),
        (4,'VPN设备'),
    )
    sub_asset_type = models.SmallIntegerField(choices=sub_assset_type_choices,verbose_name="网络设备类型",default=0)

    vlan_ip = models.GenericIPAddressField(u'VlanIP',blank=True,null=True)
    intranet_ip = models.GenericIPAddressField(u'内网IP',blank=True,null=True)
    #sn = models.CharField(u'SN号',max_length=128,unique=True)
    #manufactory = models.CharField(verbose_name=u'制造商',max_length=128,null=True, blank=True)
    model = models.CharField(u'型号',max_length=128,null=True, blank=True )
    firmware = models.CharField("固件",max_length=64,blank=True,null=True)
    port_num = models.SmallIntegerField(u'端口个数',null=True, blank=True )
    device_detail = models.TextField(u'设置详细配置',null=True, blank=True )

    class Meta:
        verbose_name = '网络设备'
        verbose_name_plural = "网络设备"

class Software(models.Model):
    '''
    only save software which company purchased
    '''
    os_types_choice = (
        (0, 'OS'),
        (1, '办公\开发软件'),
        (2, '业务软件'),

    )
    license_num = models.IntegerField(verbose_name="授权数")
    # os_distribution_choices = (('windows','Windows'),
    #                            ('centos','CentOS'),
    #                            ('ubuntu', 'Ubuntu'))
    # type = models.CharField(u'系统类型', choices=os_types_choice, max_length=64,help_text=u'eg. GNU/Linux',default=1)
    # distribution = models.CharField(u'发型版本', choices=os_distribution_choices,max_length=32,default='windows')
    version = models.CharField(u'软件/系统版本', max_length=64, help_text=u'eg. CentOS release 6.5 (Final)', unique=True)
    # language_choices = (('cn',u'中文'),
    #                     ('en',u'英文'))
    # language = models.CharField(u'系统语言',choices = language_choices, default='cn',max_length=32)
    # #version = models.CharField(u'版本号', max_length=64,help_text=u'2.6.32-431.3.1.el6.x86_64' )

    def __str__(self):
        return self.version
    class Meta:
        verbose_name = '软件/系统'
        verbose_name_plural = "软件/系统"

class CPU(models.Model):
    asset = models.OneToOneField('Asset')
    cpu_model = models.CharField(u'CPU型号', max_length=128,blank=True)
    cpu_count = models.SmallIntegerField(u'物理cpu个数')
    cpu_core_count = models.SmallIntegerField(u'cpu核数')
    memo = models.TextField(u'备注', null=True,blank=True)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(blank=True,null=True)
    class Meta:
        verbose_name = 'CPU部件'
        verbose_name_plural = "CPU部件"
    def __str__(self):
        return self.cpu_model

class RAM(models.Model):
    asset = models.ForeignKey('Asset')
    sn = models.CharField(u'SN号', max_length=128, blank=True,null=True)
    model =  models.CharField(u'内存型号', max_length=128)
    slot = models.CharField(u'插槽', max_length=64)
    capacity = models.IntegerField(u'内存大小(MB)')
    memo = models.CharField(u'备注',max_length=128, blank=True,null=True)
    create_date = models.DateTimeField(blank=True, auto_now_add=True)
    update_date = models.DateTimeField(blank=True,null=True)
    def __str__(self):
        return '%s:%s:%s' % (self.asset_id,self.slot,self.capacity)
    class Meta:
        verbose_name = 'RAM'
        verbose_name_plural = "RAM"
        unique_together = ("asset", "slot")
    auto_create_fields = ['sn','slot','model','capacity']

class Disk(models.Model):
    asset  = models.ForeignKey('Asset')
    sn = models.CharField(u'SN号', max_length=128, blank=True,null=True)
    slot = models.CharField(u'插槽位',max_length=64)
    #manufactory = models.CharField(u'制造商', max_length=64,blank=True,null=True)
    model = models.CharField(u'磁盘型号', max_length=128,blank=True,null=True)
    capacity = models.FloatField(u'磁盘容量GB')
    disk_iface_choice = (
        ('SATA', 'SATA'),
        ('SAS', 'SAS'),
        ('SCSI', 'SCSI'),
        ('SSD', 'SSD'),
    )

    iface_type = models.CharField(u'接口类型', max_length=64,choices=disk_iface_choice,default='SAS')
    memo = models.TextField(u'备注', blank=True,null=True)
    create_date = models.DateTimeField(blank=True, auto_now_add=True)
    update_date = models.DateTimeField(blank=True,null=True)

    auto_create_fields = ['sn','slot','manufactory','model','capacity','iface_type']
    class Meta:

assets/views.py
from django.shortcuts import render,HttpResponseRedirect,HttpResponse
from django.contrib.auth.decorators import login_required
from assets import models
from assets import forms,admin
from assets import assets_list
from django.core.paginator import  Paginator,EmptyPage,PageNotAnInteger
from assets import core,tables
import json
# Create your views here.
@login_required
def assetslist(request):
    print(request)
    asset_obj_list = tables.table_filter(request, admin.AssetAdmin, models.Asset)
    # asset_obj_list = models.Asset.objects.all()
    print("asset_obj_list:", asset_obj_list)
    order_res = tables.get_orderby(request, asset_obj_list, admin.AssetAdmin)
    print('----->',order_res)
    paginator = Paginator(order_res[0], admin.AssetAdmin.list_per_page)

    page = request.GET.get('page')
    try:
        asset_objs = paginator.page(page)
    except PageNotAnInteger:
        asset_objs = paginator.page(1)
    except EmptyPage:
        asset_objs = paginator.page(paginator.num_pages)

    table_obj = tables.TableHandler(request,
                                    models.Asset,
                                    admin.AssetAdmin,
                                    asset_objs,
                                    order_res
                                    )
    print(table_obj.admin_class.list_display)

    return render(request, 'assets/assetlist.html', {'table_obj': table_obj,
                                                  'paginator': paginator})
#机房列表
@login_required
def assetsarea(request):
    idclist = models.IDC.objects.all()
    paginator = Paginator(idclist,10)
    page = request.GET.get('page')
    try:
        idclist_obj = paginator.page(page)
    except PageNotAnInteger:
        idclist_obj = paginator.page(1)
    except EmptyPage:
        idclist_obj = paginator.page(paginator.num_pages)
    return render(request,'assets/assetsarea.html',{'idclist':idclist_obj})

#模块列表
def modellist(request,func):
    pass
    return HttpResponseRedirect('/assets/assetsarea/')
#机柜列表
def cabinet(request,func):
    pass
    return HttpResponseRedirect('/assets/assetsarea/')
#网络设备列表
def netlist(request):
    return render(request,'assets/networklist.html')
#ip列表
def iplist(request):
    pass
    return HttpResponseRedirect('/assets/assetsarea/')
#机房相关资产
def idcasset(request):
    pass
    return HttpResponseRedirect('/assets/assetsarea/')
#添加机房功能
# @login_required
def addarea(request):
    form = forms.IDCForm()
    if request.method == 'POST':
        form = forms.IDCForm(request.POST,request.FILES)
        if form.is_valid():
            form_data = form.cleaned_data
            new_article_obj = models.IDC(**form_data)
            new_article_obj.save()
            return HttpResponseRedirect('/assets/assetsarea/')
    return render(request,'assets/addarea.html',{'formidc':form})
#编辑机房功能
@login_required
def compiles_area(request,func):
    obj = models.IDC.objects.get(id=int(func))
    if request.method == 'POST':
        formdata = forms.IDCForm(request.POST,instance=obj)
        if formdata.is_valid():
            formdata.save()
            return HttpResponseRedirect('/assets/assetsarea/')
    form = forms.IDCForm(instance=obj)
    if form.is_valid():
        form.save()
    return render(request,'assets/addarea.html',{'formidc':form})
#机房详细信息
@login_required
def roomdetail(request,func):
    if request.method == 'GET':
        obj = models.IDC.objects.get(id=func)
        return render(request,'assets/roomdetail.html',{'form':obj})
#服务器详细资产信息
# @login_required
def hostdetail(request,page):
    if request.method == 'GET':
        obj = models.Asset.objects.get(id=page)
        return render(request,'assets/hostdetail.html',{'assets':obj})
#服务器更新功能
@login_required
def hostupdate(request):
    if request.method == 'POST':
        func = int(json.loads(request.POST.get('updateid')))
        if func:
            obj = models.Asset.objects.get(id=func)
            hostname = obj.name
            print(hostname)
            try:
                Asset = core.Assets(name=hostname)
                Asset.initialize()
                Asset.data_inject()
                return HttpResponse('ok')
            except:
                return HttpResponse('no')

templates/assets/hostdetail.html
{% extends 'base/_layout.html' %}
{% block CSS %}
<style>
    .bar .pos {
        margin-left: 5px;margin-top: 5px;float: left;position: relative;
    }
</style>
{% endblock %}
{% block content %}
<div id="content">
    <div class="container-fluid">
            <div class="">
               <!-导航栏>

              <div class="nav" style="width: 50%;margin-left: 5px;">
                  <button class="btn btn-info pos" onclick="">资产信息</button>
                  <div class="btn-group pos" >
                      <button data-toggle="dropdown" class="btn btn-success dropdown-toggle">机房 <span class="caret"></span></button>
                      <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                      </ul>
                  </div>
                  <div class="btn-group pos">
                    <button class="btn btn-primary">资产类型</button>
                    <button data-toggle="dropdown" class="btn btn-primary dropdown-toggle"><span class="caret"></span></button>
                    <ul class="dropdown-menu">
                      <li><a href="#">Action</a></li>
                      <li><a href="#">Another action</a></li>
                      <li><a href="#">Something else here</a></li>
                      <li class="divider"></li>
                      <li><a href="#">Separated link</a></li>
                    </ul>
                  </div>
                  <div class="btn-group pos">
                    <button class="btn btn-primary">资产状态</button>
                    <button data-toggle="dropdown" class="btn btn-primary dropdown-toggle"><span class="caret"></span></button>
                    <ul class="dropdown-menu">
                      <li><a href="#">Action</a></li>
                      <li><a href="#">Another action</a></li>
                      <li><a href="#">Something else here</a></li>
                      <li class="divider"></li>
                      <li><a href="#">Separated link</a></li>
                    </ul>
                  </div>
              </div>
            </div>


            <div class="span8">
                <div class="widget-box">
                    <div class="widget-content nopadding">
                        <table class="table table-bordered table-striped with-check">
                            <thead>
                                <tr>
                                    <th colspan="4" style="font-size:20px;background-color: #0e90d2">
                                    服务器基本信息
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                              <tr>
                                <th style="text-align: center">序列号:</th>
                                <td style="text-align: center">{{ assets.sn }}</td>
                                <th style="text-align: center">品牌型号:</th>
                                <td style="text-align: center">{{ assets.manufactory }}</td>
                              </tr>
                                <tr>
                                    <th style="text-align: center">系统:</th>
                                    <td style="text-align: center">{{ assets.server.os_release }}</td>
                                    <th style="text-align: center">内核:</th>
                                    <td style="text-align: center">{{ assets.server.kernelrelease }}</td>
                                </tr>

                                <tr>
                                    <th style="text-align: center">机房:</th>
                                    <td style="text-align: center">{{ assets.idc.model.idc.name }}</td>
                                    <th style="text-align: center">模块:</th>
                                    <td style="text-align: center">{{ assets.idc.model.name }}</td>
                                </tr>
                                <tr>
                                    <th style="text-align: center">机柜:</th>
                                    <td style="text-align: center">{{ assets.idc.name }}</td>
                                    <th style="text-align: center">所属业务:</th>
                                    <td style="text-align: center">{{ assets.business_unit }}</td>
                                </tr>
                                <tr>
                                   <th style="text-align: center">负责人:</th>
                                    <td style="text-align: center">{{ sqldata.principal }}</td>
                                </tr>

                                <tr>
                                    <th style="text-align: center">购买日期:</th>
                                    <td style="text-align: center">{{ assets.trade_date }}</td>
                                    <th style="text-align: center">更新日期:</th>
                                    <td style="text-align: center">{{ assets.uptime }}</td>
                                </tr>

                                <tr>
                                     <th style="text-align: center">操作员:</th>
                                    <td style="text-align: center">{{ assets.admin }}</td>
                                    <th style="text-align: center">备注:</th>
                                    <td colspan="3">{{ assets.memo }}</td>
                                </tr>
                            </tbody>
                </table>
                    </div>
                </div>
            </div>
            <div class="span6">
                <div class="widget-box">
                   <div class="widget-content nopadding">
                       <table class="table table-bordered table-striped with-check">
                           <thead>
                            <tr>
                                <th colspan="3"  class="button-primary" style="font-size:20px;background-color: #0e90d2">
                                    CPU信息
                                </th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <th style="text-align: center;width: 30%">CPU型号</th>
                                <th style="text-align: center;width: 40%">物理cpu个数</th>
                                <th style="text-align: center;width: 30%">cpu核数</th>
                            </tr>
                            <tr class="btn-default">
                                <td  style="text-align: center;">{{ assets.cpu.cpu_model }}</td>
                                <td style="text-align: center;">{{ assets.cpu.cpu_count }}</td>
                                <td style="text-align: center;">{{ assets.cpu.cpu_core_count }}</td>
                            </tr>
                            </tbody>
                       </table>
                   </div>
                </div>
            </div>
            <div class="span6">
                <div class="widget-box">
                   <div class="widget-content nopadding">
                       <table class="table table-bordered table-striped with-check">
                           <thead>
                            <tr>
                                <th colspan="4"  class="button-primary" style="font-size:20px;background-color: #0e90d2">
                                    内存信息
                                </th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <th style="text-align: center;width: 25%">SN号</th>
                                <th style="text-align: center;width: 25%">内存型号</th>
                                <th style="text-align: center;width: 25%">插槽</th>
                                <th style="text-align: center;width: 25%">内存大小(MB)</th>
                            </tr>
                            {% for ram in assets.ram_set.all %}
                            <tr class="danger">
                                <td>{{ ram.sn }}</td>
                                <td>{{ ram.model }}</td>
                                <td>{{ ram.slot }}</td>
                                <td>{{ram.capacity}}</td>
                            </tr>
                            {% endfor %}
                            </tbody>
                       </table>
                   </div>
                </div>
            </div>
            <div class="span8">
                <div class="widget-box">
                   <div class="widget-content nopadding">
                       <table class="table table-bordered table-striped with-check">
                           <thead>
                            <tr>
                                <th colspan="6"  class="button-primary" style="font-size:20px;background-color: #0e90d2">
                                    网卡信息
                                </th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <th style="text-align: center;width: 20%">网卡名</th>
                                <th style="text-align: center;width: 10%">SN号</th>
                                <th style="text-align: center;width: 10%">网卡型号</th>
                                <th style="text-align: center;width: 20%">MAC地址</th>
                                <th style="text-align: center;width: 30%">IP地址</th>
                                <th style="text-align: center;width: 30%">子网掩码</th>
                            </tr>
                            {% for nic in assets.nic_set.all %}
                            <tr class="danger">
                                <td style="text-align: center;">{{ nic.name }}</td>
                                <td style="text-align: center;">{{ nic.sn }}</td>
                                <td style="text-align: center;">{{ nic.model }}</td>
                                <td style="text-align: center;">{{ nic.macaddress }}</td>
                                <td style="text-align: center;">{{ nic.ipaddress }}</td>
                                <td style="text-align: center;">{{ nic.netmask }}</td>
                            </tr>
                            {% endfor %}
                            </tbody>
                       </table>
                   </div>
                </div>
            </div>
            <div class="span6">
                <div class="widget-box">
                   <div class="widget-content nopadding">
                       <table class="table table-bordered table-striped with-check">
                           <thead>
                            <tr>
                                <th colspan="5"  class="button-primary" style="font-size:20px;background-color: #0e90d2">
                                    硬盘信息
                                </th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <th style="text-align: center;width: 20%">SN号</th>
                                <th style="text-align: center;width: 20%">插槽位</th>
                                <th style="text-align: center;width: 20%">制造商</th>
                                <th style="text-align: center;width: 20%">磁盘型号</th>
                                <th style="text-align: center;width: 20%">磁盘容量GB</th>
                            </tr>


                            {% for disk in assets.disk_set.all %}
                            <tr>
                                <th style="text-align: center;">{{ disk.sn }}</th>
                                <th style="text-align: center;">{{ disk.slot }}</th>
                                <th style="text-align: center;">{{ disk.manufactory }}</th>
                                <th style="text-align: center;">{{ disk.model }}</th>
                                <th style="text-align: center;">{{ disk.capacity }}</th>
                            </tr>
                            {% endfor %}

                            </tbody>
                       </table>
                   </div>
                </div>
            </div>
        </div>
</div>
{% endblock %}


{% block JS %}

{% endblock %}