cmdb/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
#  Author: Jason Wang

"""cmdb URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url,include
from django.contrib import admin
from cmdb import view
from api import rest_urls
urlpatterns = [
    url(r'^admin/', admin.site.urls,name='admin'),
    # url(r'^$',view.index,name='index'),
    url(r'^$',view.index,name="dashboard"),
    url(r'^login/$', view.acc_login,name='login',),
    url(r'^logout/$', view.acc_logout,name='logout',),
    url(r'^assets/', include('assets.urls')),
    url(r'^asset/',include('asset.urls')),
    url(r'^install/', include('install.urls')),
    url(r'^userinfo/', include('userinfo.urls')),
    url(r'^log/', include('log.urls')),
    url(r'^api/', include(rest_urls)),
    url(r'^rest_api/', include( 'snippets.urls')),
]

log/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
#  Author: Jason Wang


from django.conf.urls import url
from log import views
urlpatterns = [
    url(r'^assetslogs', views.assetslogs,name='assetslogs',),
    url(r'^executelogs', views.executelogs,name='executelogs',),
    url(r'^loginlogs', views.loginlogs,name='loginlogs',),
]

userinfo/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
#  Author: Jason Wang
from django.conf.urls import url
from userinfo import views
urlpatterns = [
    url(r'^group/$', views.group,name='group',),
    url(r'^user/$', views.user,name='user',),
    url(r'^(\w+)/adds/', views.adds,name='adds',),
    url(r'^compiles/(\w+)/(\d+)/', views.compiles,name='compiles',),
    url(r'^userdetail/(\d+)/', views.userdetail,name='userdetail',),
    url(r'^deletes/', views.deletes,name='deletes',),
]

userinfo/models.py
from django.db import models

# Create your models here.
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User,update_last_login
# Create your models here.
class UserProfile(models.Model):
    '''
    用户表
    '''
    user = models.OneToOneField(User,verbose_name='后台用户')
    #名字
    name = models.CharField(max_length=32,verbose_name='姓名')
    #头像
    head_img = models.ImageField(blank=True,null=True,upload_to="uploads/portrait",verbose_name='头像')
    #邮箱
    email = models.EmailField(max_length=64,blank=True,null=True,verbose_name='邮箱')
    #手机号
    phone = models.CharField(verbose_name='手机号',max_length=128)
    #部门
    department = models.ForeignKey('Group',verbose_name='部门',null=True,blank=True)
    #公司ip
    ip = models.GenericIPAddressField(max_length=32,verbose_name='办公IP')
    #秘钥
    secret_key = models.TextField(verbose_name='密钥')
    #备注
    memo = models.TextField(verbose_name='备注', null=True, blank=True)
    #创建时间
    create_date  = models.DateField(verbose_name='注册时间',auto_now=True)
    #是否为激活用户
    is_active = models.BooleanField(verbose_name='是否激活',default=False)
    def __str__(self):
        return self.name
    class Meta:
        verbose_name = '成员'
        verbose_name_plural = '成员'
class Group(models.Model):
    #群组名称
    name = models.CharField(max_length=64,verbose_name='部门')
    #负责人
    owner = models.ForeignKey(UserProfile,verbose_name='负责人')
    #备注
    memo = models.TextField(u'备注', null=True, blank=True)
    def __str__(self):
        return  self.name
    class Meta:
        verbose_name='部门'
        verbose_name_plural = '部门'

userinfo/forms.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
#  Author: Jason Wang

from userinfo import models
from django.forms import ModelForm
class UserForm(ModelForm):
    class Meta:   #写一个原类
        model = models.UserProfile  #关联的表
        exclude = ()         #什么字段都显示
    def __new__(cls, *args, **kwargs):
        for field_name in cls.base_fields:
            if field_name == 'head_img':
                field = cls.base_fields[field_name]
                pass
            else:
                field = cls.base_fields[field_name]
                attr_dic = {'class':'form-control',
                            'placeholder':field.help_text,
                            }
                field.widget.attrs.update(attr_dic)
        return ModelForm.__new__(cls)
class GroupForm(ModelForm):
    class Meta:   #写一个原类
        model = models.Group  #关联的表
        exclude = ()         #什么字段都显示
    def __new__(cls, *args, **kwargs):
        for field_name in cls.base_fields:
            field = cls.base_fields[field_name]
            attr_dic = {'class':'form-control',
                        'placeholder':field.help_text,
                        }
            field.widget.attrs.update(attr_dic)
        return ModelForm.__new__(cls)

userinfo/views.py
from django.shortcuts import render,HttpResponseRedirect,HttpResponse
from django.contrib.auth.decorators import login_required
from django.core.paginator import  Paginator,EmptyPage,PageNotAnInteger
# Create your views here.
from userinfo import models
from userinfo import forms
from  log.models import OperationLog
import json
@login_required
def group(request):
    grouplist = models.Group.objects.all()
    paginator = Paginator(grouplist,10)
    page = request.GET.get('page')
    try:
        grouplist_objs = paginator.page(page)
    except PageNotAnInteger:
        grouplist_objs = paginator.page(1)
    except EmptyPage:
        grouplist_objs = paginator.page(paginator.num_pages)
    return render( request, 'userinfo/group.html', { 'grouplist_objs':grouplist_objs } )
@login_required
def user(request):
    group = models.Group.objects.all()
    userlist = models.UserProfile.objects.all()
    #设置要显示的页面数量
    paginator = Paginator(userlist,10)
    page = request.GET.get('page')
    try:
        userlist_objs = paginator.page(page)
        print(userlist_objs)
    except PageNotAnInteger:
        #如果页面不是一个整数,交付第一页。
        userlist_objs = paginator.page(1)
    except EmptyPage:
        userlist_objs = paginator.page(paginator.num_pages)
    return render( request, 'userinfo/user.html', { 'userlist_objs':userlist_objs, 'group':group } )
@login_required
#添加功能
def adds(request,func):
    if func == 'user':
        form = forms.UserForm()
        if request.method == 'POST':
            form = forms.UserForm(request.POST,request.FILES)
            if form.is_valid():
                form_data = form.cleaned_data
                new_article_obj = models.UserProfile(**form_data)
                new_article_obj.save()
                #日志记录
                obj = OperationLog.objects.create(name='添加用户',
                                                  event_type=4,
                                                  detail='添加用户%s'%(request.POST['name']),
                                                  user_id=request.user.userprofile.id)
                return HttpResponseRedirect('/userinfo/user/')
        return render( request, 'userinfo/adds.html', { 'form':form } )
    elif func == 'group':
        form = forms.GroupForm()
        if request.method == 'POST':
            form = forms.GroupForm(request.POST,request.FILES)
            if form.is_valid():
                form_data = form.cleaned_data
                new_article_obj = models.Group(**form_data)
                new_article_obj.save()
                obj = OperationLog.objects.create(name='添加部门',
                                                  event_type=5,
                                                  detail='添加部门%s'%(request.POST['name']),
                                                  user_id=request.user.userprofile.id)
                return HttpResponseRedirect('/userinfo/group/')
        return render( request, 'userinfo/adds.html', { 'form':form } )
    else:
        return HttpResponseRedirect('/userinfo/user/')


@login_required
#编辑功能
def compiles(request,func,id):
    if func == 'group':
        obj = models.Group.objects.get(id=int(id))
        if request.method == 'POST':
            print(request.POST)
            formdata = forms.GroupForm(request.POST,instance=obj)
            print(formdata)
            if formdata.is_valid():
                formdata.save()
                obj = OperationLog.objects.create(name='修改部门',
                                                  event_type=5,
                                                  detail='修改部门%s信息'%(request.POST['name']),
                                                  user_id=request.user.userprofile.id)
                return HttpResponseRedirect('/userinfo/group/')
            else:
                return render( request, 'userinfo/edit.html', { 'form':formdata } )
        # obj = models.Group.objects.get(id=int(id))
        form = forms.GroupForm(instance=obj)
        if form.is_valid():
            form.save()
        return render( request, 'userinfo/edit.html', { 'form':form } )
    elif func == 'user':
        obj = models.UserProfile.objects.get(id=int(id))
        if request.method == 'POST':
            # request.POST = request.POST.copy()
            # from userinfo import core
            # core.upload_file_img(request,request.FILES['head_img'])
            formdata = forms.UserForm(request.POST,request.FILES,instance=obj)
            if formdata.is_valid():
                formdata.save()
                obj = OperationLog.objects.create(name='修改用户',
                                                  event_type=4,
                                                  detail='修改用户%s信息'%(request.POST['name']),
                                                  user_id=request.user.userprofile.id)
                return HttpResponseRedirect('/userinfo/user/')
            else:
                return render( request, 'userinfo/edit.html', { 'form':formdata } )
        form = forms.UserForm(instance=obj)
        if form.is_valid():
            form.save()
        return render( request, 'userinfo/edit.html', { 'form':form } )
    else:
         return HttpResponseRedirect('/userinfo/user/')
#删除用户或组操作
def deletes(request):
    Id = json.loads(request.POST.get('DeleteId'))
    name = json.loads(request.POST.get('DeleteName'))
    if name == 'group':
        obj = models.Group.objects.filter(id=int(Id)).delete()
        objlog = OperationLog.objects.create(name='删除部门',
                                                  event_type=5,
                                                  detail='删除部门%s'%(request.POST['name']),
                                                  user_id=request.user.userprofile.id)
        return HttpResponse(json.dumps('ok'))
    elif name == 'user':
        obj = models.UserProfile.objects.filter(id=int(Id)).delete()
        objlog = OperationLog.objects.create(name='删除用户',
                                                  event_type=4,
                                                  detail='删除用户%s'%(request.POST['name']),
                                                  user_id=request.user.userprofile.id)
        return HttpResponse(json.dumps('ok'))

def userdetail(request,func):
    objuser = models.UserProfile.objects.get(id=func)
    print(objuser.__dict__)
    return render( request, 'userinfo/userdetail.html', { 'objuser':objuser } )

# Create your views here.

templates/userinfo/edit.html
{% extends 'base/_layout.html' %}

{% block content %}
    <div  id="content">
        <div class="container-fluid">
            <div class="row-fluid">
                <div class="span6">
                    <div class="widget-title">
                        <h5>修改基本信息</h5>
                    </div>
                    <div class="widget-content nopadding">
                        <form   role="form" class="form-horizontal" action="" method="post" >{% csrf_token %}
                       {% for field in form %}
                             <div class="control-group">
                                {% if field.field.required %}
                                    <label  class="col-sm-2 control-label ">*{{ field.label }}</label>
                                {% else %}
                                    <label style="font-weight: normal" class="col-sm-2 control-label text-left">{{ field.label }}</label>
                                {% endif %}
                                {% if field.name == 'head_img' %}
                                    <div class="col-sm-2" style="border: solid white 0;">
                                    {{ field }}
                                    </div>
                                {% else %}
                                 <div class="col-sm-6">
                                    {{ field }}
                                  {% if field.errors %}
                                     <ul>
                                        {% for error in field.errors %}
                                            <li style="color:red">{{ error }}</li>
                                        {% endfor %}
                                     </ul>
                                  {% endif %}
                                </div>
                             {% endif %}
                              </div>
                           {% endfor %}
                           <div class="form-group right">
                                    <div class="col-sm-4 col-sm-offset-2">
                                    <button class="btn btn-white" type="reset">取消</button>
                                    <button id="submit_button" class="btn btn-primary" type="submit">确认保存</button>
                                    </div>
                                    </div>
                    </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/userinfo/group.html
{% extends 'base/_layout.html' %}
{% load mytag %}
{% block content %}
    <div id="content">
        <div id="content-header">
            <div id="breadcrumb">
                <a href="{% url 'group' %}" title="Go to Home" class="tip-bottom">
                    <i class="icon-home"></i> 部门
                </a>
            </div>
        </div>
        <div class="container-fluid">
            <div class="span9">
               <!-导航栏>

              <div class="nav" style="width: 50%;margin-left: 5px;">
                  <button class="btn btn-info pos" onclick="">部门信息</button>
                  <div class="btn-group pos" >
                      <button data-toggle="dropdown" class="btn btn-success dropdown-toggle">部门类型 <span class="caret"></span></button>
                      <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                      </ul>
                  </div>
              </div>
              <div class="widget-box span9">
                    <div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
                      <h5>操作部门</h5>
                    </div>
                    <div class="widget-content nopadding">
                      <form class="form-horizontal">
                        <div  style="padding-left: 0;float: left">
                            <a href="/member/group/adds/" class="btn btn-sm btn-primary ">添加部门 </a>
                            <a href="#" name="batchdel" class="btn btn-sm btn-warning ">批量删除 </a>
                        </div>
                        <div  style="padding-right: 0;">
                             <div class="input-group inline-group">
                                <input type="text" style="float: right;width: 50px" id="search_input" name="keyword" value="" placeholder="Search">
                                <input type="text" style="display: none">
                                <div class="input-group-btn">
                                    <button id='search_btn' href="#" type="button"  style="float: right" class="btn  btn-primary search-btn"  onclick="">
                                        - 搜索 -
                                    </button>
                                    <button type="button" href="#" name="export" style="float: right" class="btn btn-sm btn-success search-btn-excel">
                                        - 导出 -
                                    </button>
                                </div>
                             </div>
                        </div>
                        <div class="navbar-form">

                        <table class="table table-bordered table-striped with-check">
                            <thead>
                                <tr>
                                    <th><input id="checkall" type="checkbox"  name="checkall" value="checkall" data-editable='false' onclick="check_all('asset_form')"></th>
                                    <th style="text-align: center">部门名称</th>
                                    <th class="text-center">负责人</th>
                                    <th class="text-center">联系方式</th>
                                    <th class="text-center">成员数</th>
                                    <th class="text-center">操作</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for group in grouplist_objs %}
                                <tr class="gradeX">
                                    <td class="text-center" name="id" value="{{ group.id }}" data-editable='false'>
                                        <input name="id" value="{{ group.id }}" type="checkbox" class="i-checks">
                                    </td>
                                    <td class="text-center hostname"> <a href="#">{{ group.name }}</a></td>
                                    <td class="text-center">{{ group.owner }}</td>
                                    <td class="text-center">{{ group.owner.phone }}</td>
                                    <td class="text-center">{{ group.userprofile_set.count }}</td>
                                    <td  style="text-align: center">
                                        <a href="/userinfo/compiles/group/{{ group.id }}/" class="btn btn-xs btn-info">编辑</a>
                                        <a name="deletegroup" value="#" class="btn btn-xs btn-danger">删除</a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                      </div>

                      <div class="col-sm-6">
                            </div>
                            <div class="col-sm-6">
                                    <div class="dataTables_paginate paging_simple_numbers" id="editable_paginate">
                                        <ul class="pagination" style="margin-top: 0; float: right">
                                        {% if grouplist_objs.has_previous %}
                                                <li class="paginate_button previous disabled" aria-controls="editable" tabindex="0" id="editable_previous">
                                                     <a class="?page={{ grouplist_objs.previous_page_number }}" href="#">Previous</a>
                                                </li>
                                        {% endif %}
                                         {% for page_num in grouplist_objs.paginator.page_range %}
                                            {% gusee_page grouplist_objs.number page_num %}
                                        {% endfor %}
                                        {% if grouplist_objs.has_next %}
                                                <li class="paginate_button next disabled" aria-controls="editable" tabindex="0" id="editable_next">
                                                    <a class="page" href="#">Next</a>
                                                </li>
                                                {% endif %}
                                        </ul>
                                    </div>
                            </div>
                      </form>
                    </div>
              </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block JS %}
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/plugins/sweetalert/sweetalert.min.js"></script>
    <script>
                            /*全选功能*/
                    $(document).ready(function() {
                        $("input[id=checkall]").click(
                                function () {
                                    if (this.checked) {
                                        $("input[type=checkbox]").prop('checked', true)
                                    } else {
                                        $("input[type=checkbox]").prop('checked', false)
                                    }
                                }
                        );
                        $('a[name="deletegroup"]').click(
                                function () {
{#                                    console.log('123')#}
                                    var delgroup = $(this).parent().parent().children("td[name='id']").attr("value");
                                    swal({
                                          title: "你确定要删除吗?",
                                          text: "部门删除后就不能恢复了",
                                          type: "warning",
                                          showCancelButton: true,
                                          confirmButtonColor: "#DD6B55",
                                          confirmButtonText: "Yes, delete it!",
                                          closeOnConfirm: false
                                        },
                                        function(){
                                            alert(delgroup);
                                            $.post("{% url 'deletes' %}", {DeleteId:JSON.stringify(delgroup),DeleteName:JSON.stringify('group')},
                                                    function(callback){
                                                    });
                                            swal("删除!", "部门删除成功", "success");

                                        });
                                    $(this).parent().parent().remove();
                                }
                        );
                        $('button[name="export"]').click(
                                function(){
                                     $('#assetform').table2excel({ // 选择器选择要到处的表格，也就是根据原表格构建的表格
                                        exclude: ".btn-xs",
                                        name: "Excel Document Name",
                                        filename: "部门列表", // 导出的文件名
                                        fileext: ".xls" // 导出的文件扩展名
                                        });
                                }
                        );
                            $('a[id="batchdel"]').click(
                                    function () {
                                        alert('删除你脑袋删除');
                                    }
                            )

                        $('a[name="batchdel"]').click(function () {
                                swal("谁给你的勇气删除的")
                        });
                   });
{#http://t4t5.github.io/sweetalert/#}
                            </script>
{% endblock %}

templates/userinfo/userdetail.html
{% extends 'base/_layout.html' %}
{% load mytag %}
{% block content %}
    <div id="content">
        <div id="content-header">
            <div id="breadcrumb">
                <a href="{% url 'group' %}" title="Go to Home" class="tip-bottom">
                    <i class="icon-home"></i> 部门
                </a>
            </div>
        </div>
        <div class="container-fluid">
            <div class="span9">
               <!-导航栏>
                <div class="widget-box">
                      <section class="panel">
                          <div class="user-heading round">
                              <a href="#">
                                  <img src="/static/{{ objuser.head_img | cut_url }}" alt="">
                              </a>
                              <h1>{{ objuser.name }}</h1>
                              <p>{{ objuser.email }}</p>
                          </div>
                          <ul class="nav nav-pills nav-stacked">
                              <li class="active"><a href="profile.html"> <i class="icon-user"></i> Profile</a></li>
                              <li><a href=""> <i class="icon-calendar"></i> Recent Activity <span class="label label-danger pull-right r-activity">9</span></a></li>
                              <li><a href=""> <i class="icon-edit"></i> Edit profile</a></li>
                          </ul>
                      </section>
                  </div>
                  <div class="widget-box">
                      <h1>详细</h1>
                      <div class="widget-title">
                              个人资料
                      </div>
                      <div class="widget-content">
                            <table class="table table-bordered table-striped">
                              <thead>
                                <tr>
                                  <th>类别</th>
                                  <th>属性</th>
                                </tr>
                              </thead>
                              <tbody>
                                <tr>
                                  <td><span class="label">用户名</span></td>
                                  <td style="text-align: center">{{ objuser.name }}</td>
                                </tr>
                                <tr>
                                  <td><span class="label label-success">登录账户</span></td>
                                  <td style="text-align: center">{{ objuser.user }} </td>
                                </tr>
                                <tr>
                                  <td><span class="label label-warning">部门</span></td>
                                  <td style="text-align: center">{{ objuser.department }}</td>
                                </tr>
                                <tr>
                                  <td><span class="label label-important">创建时间</span></td>
                                  <td style="text-align: center">{{ objuser.create_date }}</td>
                                </tr>
                                <tr>
                                  <td><span class="label label-info">IP</span></td>
                                  <td style="text-align: center">{{ objuser.ip }}</td>
                                </tr>
                                <tr>
                                  <td><span class="label label-inverse">Email </span></td>
                                  <td style="text-align: center">{{ objuser.email }}</td>
                                </tr>
                                <tr>
                                  <td><span class="label label-inverse">Phone </span></td>
                                  <td style="text-align: center">{{ objuser.phone }}</td>
                                </tr>
                              </tbody>
                            </table>
                      </div>
                  </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block JS %}
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/plugins/sweetalert/sweetalert.min.js"></script>
    <script>
                            /*全选功能*/
                    $(document).ready(function() {
                        $("input[id=checkall]").click(
                                function () {
                                    if (this.checked) {
                                        $("input[type=checkbox]").prop('checked', true)
                                    } else {
                                        $("input[type=checkbox]").prop('checked', false)
                                    }
                                }
                        );
                        $('a[name="deletegroup"]').click(
                                function () {
{#                                    console.log('123')#}
                                    var delgroup = $(this).parent().parent().children("td[name='id']").attr("value");
                                    swal({
                                          title: "你确定要删除吗?",
                                          text: "部门删除后就不能恢复了",
                                          type: "warning",
                                          showCancelButton: true,
                                          confirmButtonColor: "#DD6B55",
                                          confirmButtonText: "Yes, delete it!",
                                          closeOnConfirm: false
                                        },
                                        function(){
                                            alert(delgroup);
                                            $.post("{% url 'deletes' %}", {DeleteId:JSON.stringify(delgroup),DeleteName:JSON.stringify('group')},
                                                    function(callback){
                                                    });
                                            swal("删除!", "部门删除成功", "success");

                                        });
                                    $(this).parent().parent().remove();
                                }
                        );
                        $('button[name="export"]').click(
                                function(){
                                     $('#assetform').table2excel({ // 选择器选择要到处的表格，也就是根据原表格构建的表格
                                        exclude: ".btn-xs",
                                        name: "Excel Document Name",
                                        filename: "部门列表", // 导出的文件名
                                        fileext: ".xls" // 导出的文件扩展名
                                        });
                                }
                        );
                            $('a[id="batchdel"]').click(
                                    function () {
                                        alert('删除你脑袋删除');
                                    }
                            )

                        $('a[name="batchdel"]').click(function () {
                                swal("谁给你的勇气删除的")
                        });
                   });
{#http://t4t5.github.io/sweetalert/#}
                            </script>
{% endblock %}